name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run application with secret
      run: node js/chatbox.js
      env:
        API_KEY: ${{ secrets.API_KEY }}
